# Generated by Django 2.1.3 on 2018-11-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('Launch_Time', models.DateTimeField()),
                ('Content', models.TextField()),
            ],
        ),
    ]
