# Generated by Django 2.1.3 on 2018-12-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Edit_Time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Launch_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
