# Generated by Django 2.1.3 on 2018-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181201_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PassWord',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
