# Generated by Django 2.1.4 on 2018-12-21 13:55

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181221_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AlterField(
            model_name='article',
            name='Content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
