# Generated by Django 2.1.4 on 2018-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181221_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Content',
            field=models.TextField(),
        ),
    ]
