# Generated by Django 2.1.4 on 2018-12-22 07:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181221_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
