# Generated by Django 2.1.5 on 2019-01-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190108_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childremark',
            name='Article',
        ),
        migrations.RemoveField(
            model_name='childremark',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='childremark',
            name='ParentRemark',
        ),
        migrations.DeleteModel(
            name='childRemark',
        ),
    ]
