# Generated by Django 2.1.5 on 2019-01-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190108_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='childRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Launch_Time', models.DateTimeField(auto_now_add=True)),
                ('Edit_Time', models.DateTimeField(auto_now=True)),
                ('Content', models.CharField(max_length=256)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childRemark', to='app.Article')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myReply', to='app.User')),
                ('ParentRemark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childRemark', to='app.parentRemark')),
                ('ReplyTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
