# Generated by Django 3.0.8 on 2020-07-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_childremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='LikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='ViewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticleLike', to='app.Article')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticleLike', to='app.User')),
            ],
        ),
    ]
