# Generated by Django 3.0.8 on 2020-07-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200719_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AvatorFileName',
            field=models.CharField(default='default_avater.jpg', max_length=256),
        ),
    ]
